[theme]
base = "dark"
primaryColor = "#06B6D4"
backgroundColor = "#080C16"
secondaryBackgroundColor = "#111827"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50
